### ISSUE TITLE
What do you mean by "Hides controls to prevent detention by teacher"

### ISSUE THREAD

**Issue by A-Yamout** [FinishedManx843/Membean_Bot#1]
What do you mean by "Hides controls to prevent detention by teacher." in the version 2-version 3 update section?

BTW Nice job

**Comment by A-Yamout** [comment]
@FinishedManx843

**Comment by Sluke950** [comment]
Oh boy I made this a few years back. I believe there is a button that will hide the controls at the bottom of the screen.

**Comment by A-Yamout** [comment]
So does this still work with the membean cheating feature? @FinishedManx843

**Comment by Sluke950** [comment]
Yes I believe so. It’s been a while since I’ve used it I will have to try it again and refresh my memory.

**Comment by A-Yamout** [comment]
Nice Job, you have done the world a great favor! @FinishedManx843

**Comment by Sluke950** [comment]
Thanks!
